//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programm.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UchetBaseEntities3 : DbContext
    {
        private static UchetBaseEntities3 _context;
        public UchetBaseEntities3()
            : base("name=UchetBaseEntities3")
        {
        }

        public static UchetBaseEntities3 GetContext()
        {
            if (_context == null)
                _context = new UchetBaseEntities3();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentEducation> DocumentEducation { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<LD> LD { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<Statement> Statement { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
